name: Hajar CI - @latest

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  release:
    types:
      - created

jobs:
  publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          if [ -e 'package-lock.json' ]; then 
            npm ci
          else 
            npm install --legacy-peer-deps
          fi
      - name: Build Library
        run: npm run build --if-present
      - name: Test & Lint
        run: |
          npm run test:coverage --if-present
          npm run lint --if-present
      - name: Publish to NPM main tag
        run: npm publish
